import {
  faCar,
  faUsers,
  faUserTie,
  faWallet,
  faClipboardList,
  faRoute,
  faTicket,
  faChartLine,
  faCommentDots,
  faStar,
  faPercent,
  faMoneyBillTrendUp,
  faBell,
  faLayerGroup,
} from "@fortawesome/free-solid-svg-icons";

export const dashboardNavigation = [
  { key: "sidebar.drivers", path: "driver", icon: faCar, roles: ["admin", "employee"] },
  { key: "sidebar.passengers", path: "passenger", icon: faUsers, roles: ["admin", "employee"] },
  { key: "sidebar.employees", path: "employee", icon: faUserTie, roles: ["admin"] },
  { key: "sidebar.category", path: "category", icon: faLayerGroup, roles: ["admin"] },
  { key: "sidebar.wallet", path: "wallet", icon: faWallet, roles: ["admin", "employee"] },
  { key: "sidebar.auditLog", path: "auditLog", icon: faClipboardList, roles: ["admin"] },
  { key: "sidebar.trips", path: "trips", icon: faRoute, roles: ["admin", "employee"] },
  { key: "sidebar.booking", path: "booking", icon: faTicket, roles: ["admin", "employee"] },
  { key: "sidebar.reports", path: "Reports", icon: faChartLine, roles: ["admin", "employee"] },
  { key: "sidebar.complaints", path: "complaints", icon: faCommentDots, roles: ["admin", "employee"] },
  { key: "sidebar.rating", path: "rating", icon: faStar, roles: ["admin", "employee"] },
  { key: "sidebar.rateCommission", path: "rateCommission", icon: faPercent, roles: ["admin"] },
  { key: "sidebar.revenue", path: "RevenueR", icon: faMoneyBillTrendUp, roles: ["admin", "employee"] },
  { key: "sidebar.notifications", path: "Notifi", icon: faBell, roles: ["admin", "employee"] },
];
